# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: quadrature
# Can be C or C++
language: C++

optimization: O3

# MCU settings
targetMCU: stm32g4x
cpu: cortex-m4 # type of cpu e.g. cortex-m4
fpu: fpv4-sp-d16 # Defines how floating points are defined. Can be left empty.
floatAbi: -mfloat-abi=hard
ldscript: STM32G431C8Tx_FLASH.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions: 
  - USE_HAL_DRIVER
  - STM32G431xx
  - ARM_MATH_CM4

cxxDefinitions: 
  - USE_HAL_DRIVER
  - STM32G431xx
  - ARM_MATH_CM4

asDefinitions: []

# Compiler definition files. you can add a single files or an array of files for different definitions.
# The file is expected to have a definition each new line.
# This allows to include for example a .definition file which can be ignored in git and can contain
# This can be convenient for passing along secrets at compile time, or generating a file for per device setup.
cDefinitionsFile:
cxxDefinitionsFile:
asDefinitionsFile:

# Compiler flags
cFlags: []
cxxFlags: []
assemblyFlags: []
linkerFlags: 
  - -specs=nano.specs


# libraries to be included. The -l prefix to the library will be automatically added.
libraries: 
  - c
  - m
  - nosys
  - arm_cortexM4lf_math

# Library directories. Folders can be added here that contain custom libraries.
libraryDirectories: 
  - Drivers/CMSIS/DSP/Lib/GCC


# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes: 
  - "**/Examples/**"
  - "**/examples/**"
  - "**/Example/**"
  - "**/example/**"
  - "**_template.*"


# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories: 
  - Middlewares/USB_Device/App
  - Middlewares/USB_Device/Target
  - Drivers/STM32G4xx_HAL_Driver/Inc
  - Drivers/STM32G4xx_HAL_Driver/Inc/Legacy
  - Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  - Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
  - Drivers/CMSIS/Device/ST/STM32G4xx/Include
  - Drivers/CMSIS/Include
  - Drivers/CMSIS/DSP/Include
  - Middlewares/Third_Party/FreeRTOS/Source/include 
  - Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 
  - Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
  - quadrature/**


# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:  
  - startup_stm32g431xx.s
  - Middlewares/USB_Device/Target/usbd_conf.c
  - Middlewares/USB_Device/App/usb_device.c
  - Middlewares/USB_Device/App/usbd_desc.c
  - Middlewares/USB_Device/App/usbd_cdc_if.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pcd.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pcd_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_usb.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cordic.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c
  - Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c
  - Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
  - Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
  - Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
  - Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
  - Middlewares/Third_Party/FreeRTOS/Source/**
  - quadrature/**


# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: true

# Custom makefile rules
# Here custom makefile rules can be added to the STM32Make.make file
# an example of how this can be used is commented out below.
customMakefileRules:
# - command: sayhello
#   rule: echo "hello"
#   dependsOn: $(BUILD_DIR)/$(TARGET).elf # can be left out    

# Additional flags which will be used when invoking the make command
makeFlags:
# - -O  # use this option when the output of make is mixed up only works for make version 4.0 and upwards
# - --silent # use this option to silence the output of the build
    